version: "3.5"

services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on:
      - db
    env_file:
      - ./.env.development
    environment:
      SPRING_PORT: 8080
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "1GB"
    network_mode: host

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    depends_on:
      - db
    env_file:
      - ./.env.development
    environment:
      SPRING_PORT: 8081
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "1GB"
    network_mode: host

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"
    network_mode: host

  db:
    image: postgres:16.0-alpine3.18
    hostname: database
    env_file:
      - ./.env.development
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"
    network_mode: host
