version: "3.5"

services:
  db:
    image: postgres:16.0-alpine3.18
    hostname: database
    env_file:
      - ./.env.development
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1GB"
