version: "3.5"

services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on:
      - db
    environment:
      SPRING_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/local_database
      SPRING_DATASOURCE_USERNAME: local_user
      SPRING_DATASOURCE_PASSWORD: local_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "3GB"
    network_mode: host

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    depends_on:
      - db
    environment:
      SPRING_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/local_database
      SPRING_DATASOURCE_USERNAME: local_user
      SPRING_DATASOURCE_PASSWORD: local_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    deploy:
      resources:
        limits:
          cpus: "3"
          memory: "3GB"
    network_mode: host

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2GB"
    network_mode: host

  db:
    image: postgres:16.0-alpine3.18
    hostname: database
    env_file:
      - ./.env.development
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "0.7GB"
    network_mode: host
